FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        clang \
        clang-tools-extra \
        cmake \
        gcc-c++ \
        git \
        make \
        netcdf-devel \
    && dnf clean all
