FROM docker.io/intel/oneapi-hpckit:latest

RUN wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | \
  gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics-archive-keyring.gpg

RUN apt update \
    && apt -y install \
      build-essential \
      ca-certificates \
      cmake \
      cmake-curses-gui \
      git \
      make \
    && apt clean

ENV CC=icx
ENV CXX=icpx

COPY . /miem/

RUN mkdir /build \
    && cd /build \
    && cmake \
        -D CMAKE_BUILD_TYPE=Release \
        /miem \
    && make -j 8

WORKDIR /build
