from nvcr.io/nvidia/nvhpc:25.1-devel-cuda12.6-ubuntu24.04

RUN apt update \
    && apt -y install \
        build-essential \
        ca-certificates \
        cmake \
        cmake-curses-gui \
        git \
        libnetcdf-dev \
        make \
    && apt clean

ENV CC=nvc
ENV CXX=nvc++

COPY . /miem/

RUN mkdir /build \
    && cd /build \
    && cmake \
        -D CMAKE_BUILD_TYPE=Release \
        -D MIEM_ENABLE_TESTS=ON \
        /miem \
    && make -j 8

WORKDIR /build
