# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

import os
import sys
import datetime
import re
import subprocess
sys.path.insert(0, os.path.abspath('.'))

DOCS_SOURCE_DIR = os.path.abspath(os.path.dirname(__file__))
REPO_ROOT_DIR = os.path.abspath(os.path.join(DOCS_SOURCE_DIR, '..', '..'))
BUILD_DIR = os.path.join(REPO_ROOT_DIR, 'build')
DOXYGEN_XML_DIR = os.path.join(BUILD_DIR, 'docs', 'doxygen', 'xml')


def _run_command(command, cwd=None):
    try:
        subprocess.run(command, cwd=cwd, check=True)
    except (OSError, subprocess.CalledProcessError) as exc:
        sys.stderr.write(f"Command failed: {command}\n{exc}\n")
        raise


def _ensure_doxygen_xml():
    # On Read the Docs the Doxygen XML is generated by the CMake build in the
    # .readthedocs.yaml pre_build step; this hook makes conf.py self-sufficient
    # for a bare ``sphinx-build`` as well.
    read_the_docs_build = os.environ.get('READTHEDOCS', None) == 'True'
    if not read_the_docs_build:
        return

    cache_file = os.path.join(BUILD_DIR, 'CMakeCache.txt')
    if not os.path.exists(cache_file):
        _run_command([
            'cmake',
            '-S', REPO_ROOT_DIR,
            '-B', BUILD_DIR,
            '-D', 'MIEM_BUILD_DOCS=ON',
            '-D', 'MIEM_ENABLE_TESTS=OFF',
        ])

    _run_command([
        'cmake',
        '--build', BUILD_DIR,
        '--target', 'Doxygen',
    ])

# -- Project information -----------------------------------------------------

project = 'MIEM'
copyright = f'2024-{datetime.datetime.now().year}, NSF-NCAR/ACOM'
author = 'NSF-NCAR/ACOM'

regex = r'project\(\w+\s+VERSION\s+(\d+\.\d+\.\d+)'
version = '0.0.0'
# read the version from the cmake files
with open(os.path.join(REPO_ROOT_DIR, 'CMakeLists.txt'), 'r') as f:
    for line in f:
        match = re.match(regex, line)
        if match:
            version = match.group(1)
release = f'{version}'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'sphinx_copybutton',
    'sphinx_design',
    'sphinxcontrib.bibtex',
    'sphinx.ext.intersphinx',
]

bibtex_bibfiles = ['references.bib']
suppress_warnings = ["bibtex.missing_field"]

breathe_default_project = "miem"
breathe_projects = {
    "miem": DOXYGEN_XML_DIR
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# -- Link to Intersphinx Mappings --------------------------------------------

intersphinx_mapping = {
    'musica': ('https://ncar.github.io/musica/', None),
    'micm': ('https://ncar.github.io/micm/', None),
    'mc': ('https://ncar.github.io/MechanismConfiguration/', None),
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'pydata_sphinx_theme'

html_theme_options = {
    "external_links": [],
    "github_url": "https://github.com/NCAR/miem",
    "navbar_end": ["navbar-icon-links"],
    "pygment_light_style": "tango",
    "pygment_dark_style": "monokai"
}

html_css_files = [
    'custom.css'
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory.
html_static_path = ['_static']


def setup(app):
    app.connect("builder-inited", lambda _app: _ensure_doxygen_xml())
